'''
Runs the network with the parameters load from a file generated by 'find_oscillations.py'
'''


import pickle
import os
from src.RNN import RNN
from matplotlib import pyplot as plt
import numpy as np
from src.state_function import *

N = 7
lmbd = 0.2
k = 0.01
dt = 0.1
file_name = f"params_{N}_{lmbd}_{k}.pkl"
param_dict = pickle.load(open(os.path.join("../", "data", file_name), "rb+"))

rnn = RNN(dt, lmbd, k,  param_dict["W"], param_dict["b"], maxlen=3000000)
T = 200001
rnn.run(T)

signal_dict = dict()
signal_dict["dt"] = dt
signal_dict["h"] = np.array(rnn.h_history)
signal_dict["s"] = s(lmbd, k, np.array(rnn.h_history))
signal_dict["params"] = param_dict

file_name = f"targets_{N}_{lmbd}_{k}_{dt}.pkl"
file_path = os.path.join("../", "data", file_name)
pickle.dump(signal_dict, open(file_path, "wb+"))


#test load
# file_name = f"targets_{N}_{lmbd}_{k}_{dt}.pkl"
# file_path = os.path.join("../", "data", file_name)
# signal_dict = pickle.load(open(file_path, "rb+"))
# h_out = signal_dict["h"]
# plt.plot(h_out[-1000:])
# plt.show()